services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672"
      - "15672:15672"
  payment:
    build:
      context: .
    image: robotshop/rs-payment:2.1.0
    depends_on:
      - rabbitmq
    ports:
      - "31080:8080"
